# Copyright (c) Meta Platforms, Inc. and affiliates.

name: Publish HMA docker image

on:
  pull_request:
    branches:
      - main
    paths:
      - "hasher-matcher-actioner/version.txt"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    name: Build and Publish Hasher Matcher Actioner Docker Image to registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read version
        id: version
        run: echo "VERSION=$(cat hasher-matcher-actioner/version.txt)" >> $GITHUB_ENV

      - name: test environment
        run: |
        echo $VERSION
        echo ${{ env.IMAGE_NAME }}
        echo "ghcr.io/${{ github.repository }}/hma:${{ env.VERSION }}"
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Build and push
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     file: ./hasher-matcher-actioner/Dockerfile
      #     push: true
      #     tags: ghcr.io/${{ github.repository }}/hma:${{ env.VERSION }}

      # - name: Generate artifact attestation
      #   uses: actions/attest-build-provenance@v1
      #   with:
      #     subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      #     subject-digest: ${{ steps.push.outputs.digest }}
      #     push-to-registry: true
